### ISSUE TITLE
BEFORE LAUNCH CHECKLIST

### ISSUE THREAD

**Issue by evykassirer** [socraticorg/mathsteps#52]
This is to keep track of mathsteps related tasks before the launch mid-Jan:

- [x] make a ROADMAP.md based on Socratic coverage goals [see it here](https://github.com/socraticorg/mathsteps/blob/master/ROADMAP.md)
- [x] go through TODOs in code and move to github issues @evykassirer

code reorg:
- [x] #57 @evykassirer
- [x] do a lookover for structure consistency? (@aelnaiem)

after we finalize index.js:
- [x] #61 publish mathsteps to npm
- [x] #61 update the README to just have usage instructions (and how to download on npm) @evykassirer

doesn't necessarily have to be before launch:
- [ ] make a wiki on GitHub (stuff like blog post, explanations, code structure)
- [ ] Add remove unnecessary parens in NodeStatus creation, and get rid of addStep (in both expression and equations)

**Comment by evykassirer** [comment]
moved the rest to their own issues #66 #67
